CREATE TYPE "public"."kyc_status" AS ENUM('submitted', 'responsible_reviewed', 'compliance_reviewed', 'specialist_reviewed', 'completed');--> statement-breakpoint
CREATE TYPE "public"."kyc_type" AS ENUM('natural', 'legal');--> statement-breakpoint
CREATE TABLE "activity_regions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kyc_id" uuid NOT NULL,
	"region" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "kyc_documents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"type" "kyc_type" NOT NULL,
	"status" "kyc_status" DEFAULT 'submitted' NOT NULL,
	"full_name" text,
	"birth_date" varchar(20),
	"birth_country" text,
	"nationality" text,
	"document_type" text,
	"document_number" text,
	"gender" text,
	"professional_activity" text,
	"profession" text,
	"marital_status" text,
	"partner_full_name" text,
	"marital_economic_regime" text,
	"phone" varchar(30),
	"email" varchar(100),
	"company_name" text,
	"company_phone" varchar(30),
	"company_email" varchar(100),
	"registration_date" varchar(20),
	"registration_city" text,
	"tax_id" varchar(50),
	"company_purpose" text,
	"geographic_scope" text,
	"annual_revenue" text,
	"has_branches" text,
	"branches_details" text,
	"is_main_branch" text,
	"main_branch_details" text,
	"is_listed_on_regulated_market" text,
	"regulated_market_details" text,
	"representative_full_name" text,
	"representative_date_of_birth" varchar(20),
	"representative_country_of_birth" text,
	"representative_nationality" text,
	"representative_document_type" text,
	"representative_document_number" text,
	"representative_gender" text,
	"representative_professional_activity" text,
	"representative_profession" text,
	"representative_marital_status" text,
	"representative_partner_full_name" text,
	"representative_marital_economic_regime" text,
	"representative_phone" varchar(30),
	"representative_email" varchar(100),
	"fiscal_address" text,
	"fiscal_city" text,
	"fiscal_postal_code" varchar(20),
	"fiscal_country" text,
	"postal_address" text,
	"postal_city" text,
	"postal_postal_code" varchar(20),
	"postal_country" text,
	"funds_not_from_money_laundering" boolean,
	"funds_source" boolean,
	"funds_source_details" text,
	"acting_on_own_behalf" boolean,
	"acting_on_behalf_of_third_party" boolean,
	"third_party_represented" text,
	"authorized_verification" boolean,
	"no_tax_procedure" boolean,
	"legal_funds_origin" boolean,
	"business_purpose" text,
	"cash_usage" text,
	"is_risky_sector" text,
	"risky_sector" text,
	"is_pep" text,
	"is_self_exposed" text,
	"is_family_exposed" text,
	"is_associates_exposed" text,
	"has_held_public_function" text,
	"family_has_held_public_function" text,
	"close_person_has_held_public_function" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "related_persons" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kyc_id" uuid NOT NULL,
	"full_name" text NOT NULL,
	"position" text,
	"period" text,
	"country" text,
	"relationship" text
);
--> statement-breakpoint
ALTER TABLE "activity_regions" ADD CONSTRAINT "activity_regions_kyc_id_kyc_documents_id_fk" FOREIGN KEY ("kyc_id") REFERENCES "public"."kyc_documents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "related_persons" ADD CONSTRAINT "related_persons_kyc_id_kyc_documents_id_fk" FOREIGN KEY ("kyc_id") REFERENCES "public"."kyc_documents"("id") ON DELETE cascade ON UPDATE no action;