/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ClientIndexImport } from './routes/client/index'
import { Route as PreviewClientIdImport } from './routes/preview/$clientId'
import { Route as ClientClientIdImport } from './routes/client/$clientId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ClientIndexRoute = ClientIndexImport.update({
  path: '/client/',
  getParentRoute: () => rootRoute,
} as any)

const PreviewClientIdRoute = PreviewClientIdImport.update({
  path: '/preview/$clientId',
  getParentRoute: () => rootRoute,
} as any)

const ClientClientIdRoute = ClientClientIdImport.update({
  path: '/client/$clientId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/client/$clientId': {
      preLoaderRoute: typeof ClientClientIdImport
      parentRoute: typeof rootRoute
    }
    '/preview/$clientId': {
      preLoaderRoute: typeof PreviewClientIdImport
      parentRoute: typeof rootRoute
    }
    '/client/': {
      preLoaderRoute: typeof ClientIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ClientClientIdRoute,
  PreviewClientIdRoute,
  ClientIndexRoute,
])

/* prettier-ignore-end */
